---

- name: "Setup"
  gather_facts: True
  hosts: localhost
  vars:
    zpool:
      name: "rpool"

  tasks:
    - name: "Gather packages"
      package_facts:
        manager: "auto"

    - become: True
      block:

        - name: "Debian sources"
          ansible.builtin.copy:
            dest: "/etc/apt/sources.list"
            mode: "0644"
            content: |
              deb http://deb.debian.org/debian/ testing main contrib non-free non-free-firmware
              deb-src http://deb.debian.org/debian/ testing main contrib non-free non-free-firmware
              
              deb http://security.debian.org/debian-security testing-security main contrib non-free non-free-firmware
              deb-src http://security.debian.org/debian-security testing-security main contrib non-free non-free-firmware
              
              deb http://deb.debian.org/debian/ testing-updates main contrib non-free non-free-firmware
              deb-src http://deb.debian.org/debian/ testing-updates main contrib non-free non-free-firmware
          register: "sources_list"

        - name: "Apt upgrade"
          ansible.builtin.apt:
            update_cache: True
            upgrade: "full"
            dpkg_options: "force-confnew,force-confdef"
          register: "apt_upgrade"
          when: sources_list.changed

        - name: "Reboot"
          ansible.builtin.reboot:
          when: apt_upgrade.changed

        - name: "Install tools"
          ansible.builtin.apt:
            package:
              - "vim"

        - name: "Wi-Fi interface config template"
          ansible.builtin.copy:
            content: |
              allow-hotplug {{ item }}
              iface {{ item }} inet dhcp
                  wpa-ssid "ssid"
                  wpa-psk "psk"
            dest: "/etc/network/interfaces.d/{{ item }}"
            force: False
            mode: "0644"
          loop: "{{ ansible_interfaces }}"
          when: "'wlp' in item"

        # https://gist.github.com/Vertecedoc4545/3b077301299c20c5b9b4db00f4ca6000
        - name: "Build dependencies"
          ansible.builtin.apt:
            package:
              - meson
              - wget
              - build-essential
              - ninja-build
              - cmake-extras
              - cmake
              - gettext
              - gettext-base
              - fontconfig
              - libfontconfig-dev
              - libffi-dev
              - libxml2-dev
              - libdrm-dev
              - libxkbcommon-x11-dev
              - libxkbregistry-dev
              - libxkbcommon-dev
              - libpixman-1-dev
              - libudev-dev
              - libseat-dev
              - seatd
              - libxcb-dri3-dev
              - libvulkan-dev
              - libvulkan-volk-dev
              #- vulkan-validationlayers-dev (N/A?)
              - libvkfft-dev
              - libgulkan-dev
              - libegl-dev
              - libgles2
              - libegl1-mesa-dev
              - glslang-tools
              - libinput-bin
              - libinput-dev
              - libxcb-composite0-dev
              - libavutil-dev
              - libavcodec-dev
              - libavformat-dev
              - libxcb-ewmh2
              - libxcb-ewmh-dev
              - libxcb-present-dev
              - libxcb-icccm4-dev
              - libxcb-render-util0-dev
              - libxcb-res0-dev
              - libxcb-xinput-dev
              - xdg-desktop-portal-wlr
              #- hwdata-dev (N/A?):
              - hwdata

        - name: "Create /tmp/setup/repositories"
          ansible.builtin.file:
            path: "/tmp/setup/repositories"
            state: "directory"

        - name: "Git checkout Hyprland"
          ansible.builtin.git:
            dest: "/tmp/setup/repositories/Hyprland"
            force: True
            repo: "https://github.com/hyprwm/Hyprland.git"
            version: "v0.24.1"

        - name: "Git checkout libdisplay-info"
          ansible.builtin.git:
            dest: "/tmp/setup/repositories/libdisplay-info"
            force: True
            repo: "https://gitlab.freedesktop.org/emersion/libdisplay-info.git"
            version: "0.1.1"

        - name: "Git checkout wayland"
          ansible.builtin.git:
            dest: "/tmp/setup/repositories/wayland"
            force: True
            repo: "https://gitlab.freedesktop.org/wayland/wayland.git"
            version: "1.22.0"

        - name: "Git checkout wayland-protocols"
          ansible.builtin.git:
            dest: "/tmp/setup/repositories/wayland-protocols"
            force: True
            repo: "https://gitlab.freedesktop.org/wayland/wayland-protocols.git"
            version: "1.31"

        - name: "Build libdisplay-info"
          ansible.builtin.shell: |
            mkdir -p /tmp/setup/repositories/libdisplay-info/build && cd "$_"
            meson setup --prefix=/usr --buildtype=release
            ninja
            ninja install
          args:
            executable: /bin/bash

        - name: "Build wayland"
          ansible.builtin.shell: |
            mkdir -p /tmp/setup/repositories/wayland/build && cd "$_"
            meson setup .. --prefix=/usr --buildtype=release -Ddocumentation=false
            ninja
            ninja install
          args:
            executable: /bin/bash

        - name: "Build wayland-protocols"
          ansible.builtin.shell: |
            mkdir -p /tmp/setup/repositories/wayland-protocols/build && cd "$_"
            meson setup --prefix=/usr --buildtype=release
            ninja
            ninja install
          args:
            executable: /bin/bash

#        - name: "Install utils"
#          ansible.builtin.apt:
#            package:
#              - "debootstrap"
#              - "dkms"
#              - "gdisk"
#              - "linux-headers-{{ ansible_kernel }}"
#              - "parted"
#              - "zfs-dkms"
#              - "zfs-zed"
#              - "zfsutils-linux"
#
#        - ansible.builtin.set_fact:
#            disks: "{{ ansible_facts.devices | select('match', '^nvme') | default(false) }}"
#
#        - ansible.builtin.set_fact:
#            disk:
#              device: "/dev/{{ disks | length > 1 or disks | first | default(false) }}"
#              name: "{{ disks | length > 1 or disks | first | default(false) }}"
#            partitions:
#              numbers:
#                boot: 1
#                swap: 2
#                pool: 3
#
#        - ansible.builtin.set_fact:
#            partitions:
#              devices:
#                boot: "{{ disk.device }}p{{ partitions.numbers.boot }}"
#                swap: "{{ disk.device }}p{{ partitions.numbers.swap }}"
#                pool: "{{ disk.device }}p{{ partitions.numbers.pool }}"
#              names:
#                boot: "{{ disk.name }}p{{ partitions.numbers.boot }}"
#                swap: "{{ disk.name }}p{{ partitions.numbers.swap }}"
#                pool: "{{ disk.name }}p{{ partitions.numbers.pool }}"
#              numbers: "{{ partitions.numbers }}"
#
#        - ansible.builtin.shell: |
#            umount -nqR /mnt
#            zpool export -af
#
#            zpool labelclear -f "{{ partitions.devices.pool }}"
#            wipefs -af "{{ disk.device }}"
#            sgdisk --zap-all "{{ disk.device }}"
#            partprobe "{{ disk.device }}"
#
#            sgdisk -n "{{ partitions.numbers.boot }}:1m:+500m" -t "{{ partitions.numbers.boot }}:ef00" -c 0:esp "{{ disk.device }}"
#            # sgdisk -n "{{ partitions.numbers.swap }}:0:+9g" -t "{{ partitions.numbers.swap }}:8200" -c 0:swap "{{ disk.device }}"
#            sgdisk -n "{{ partitions.numbers.pool }}:0:-10m" -t "{{ partitions.numbers.pool }}:bf00" -c 0:pool "{{ disk.device }}"
#            partprobe "{{ disk.device }}"
#
#            echo 'insecurepassword' > /etc/zfs/{{ zpool.name }}.key
#            chmod 000 /etc/zfs/{{ zpool.name }}.key
#
#            zpool create -f -o ashift=12 \
#              -O compression=lz4 \
#              -O acltype=posixacl \
#              -O xattr=sa \
#              -O relatime=on \
#              -o autotrim=on \
#              -O encryption=aes-256-gcm \
#              -O keylocation=file:///etc/zfs/{{ zpool.name }}.key \
#              -O keyformat=passphrase \
#              -m none {{ zpool.name }} \
#              "{{ ansible_facts.devices[disk.name].partitions[partitions.names.pool].links.ids | first }}"
#
#            zfs create -o mountpoint=none {{ zpool.name }}/ROOT
#            zfs create -o mountpoint=/ -o canmount=noauto {{ zpool.name }}/ROOT/debian
#            zfs create -o mountpoint=/home {{ zpool.name }}/home
#            zpool set bootfs={{ zpool.name }}/ROOT/debian {{ zpool.name }}
#
#            zpool export {{ zpool.name }}
#            zpool import -N -R /mnt {{ zpool.name }}
#            zfs load-key -L /etc/zfs/{{ zpool.name }}.key {{ zpool.name }}
#            zfs mount {{ zpool.name }}/ROOT/debian
#            zfs mount {{ zpool.name }}/home
#            udevadm trigger
#
#            debootstrap trixie /mnt
#            mkdir -p /mnt/etc/zfs
#            cp /etc/zfs/{{ zpool.name }}.key /mnt/etc/zfs
#
#            mount -t proc proc /mnt/proc
#            mount -t sysfs sys /mnt/sys
#            mount -B /dev /mnt/dev
#            mount -t devpts pts /mnt/dev/pts
